### ISSUE TITLE
android6.0版本 871504错误

### ISSUE THREAD

**Issue by junyuz** [jpush/jmessage-phonegap-plugin#11]
按照文档中的操作步骤，集成到了cordova项目中，采用android api23版本编译时，会报871504错误，但是降级到api22编译时没有问题，个人怀疑是api23的权限问题导致的

**Comment by lhw5123** [comment]
你好，是使用的 cordova 命令行工具进行编译的吗？我这边设置为 23 进行测试，没有编译报错，871504错误码表示 Push 注册未完成，可能是 JPush 的配置有些问题，能不能把具体的错误日志贴上来呢？
