### ISSUE TITLE
Error: Cannot find plugin.xml for plugin 'package'. Please try adding it again

### ISSUE THREAD

**Issue by MarkWh1te** [jpush/jmessage-phonegap-plugin#12]
无法安装插件

cordova plugins add cordova plugin add  /home/mark/cc/jmessage-phonegap-plugin --variable APP_KEY=8b4fdeb6cde8f71c752550ed
Fetching plugin "cordova" via npm
Error: Cannot find plugin.xml for plugin 'package'. Please try adding it again.

cordova -v                                                              
6.1.1

**Comment by Yasashi** [comment]
@MarkWh1te  你好，我使用的命令如下：
```
cordova create Myproj com.myproj.jpush MyTestProj
cd Myproj
cordova platform add ios
cordova plugin add  https://github.com/jpush/jmessage-phonegap-plugin.git --variable APP_KEY=abcacdf406411fa656ee11c3
cordova plugin add org.apache.cordova.device

cordova -v
6.1.1
```
你的问题可能是你本地的存放路径不对导致的

**Comment by MarkWh1te** [comment]
@Yasashi  Thank you very much you solved my problem perfectly!
