### ISSUE TITLE
不能响应OpenNitification事件

### ISSUE THREAD

**Issue by reedseu** [jpush/jmessage-phonegap-plugin#13]
注册了"jpush.openNotification"事件，但是点击通知，不能响应，盼答复

**Comment by lhw5123** [comment]
是 Android 还是 iOS？

**Comment by reedseu** [comment]
IOS还没来及测试，目前测试的是安卓，ADT显示 reveiver貌似没进入 而普通的jpush通知是可以xiang------------------------------------------------------------------发件人：Hevin <notifications@github.com>发送时间：2016年6月21日(星期二) 14:42收件人：jpush/jmessage-phonegap-plugin <jmessage-phonegap-plugin@noreply.github.com>抄　送：reedseu <reedseu@aliyun.com>; Author <author@noreply.github.com>主　题：Re: [jpush/jmessage-phonegap-plugin] 不能响应OpenNitification事件 (#13)
是 Android 还是 iOS？—

**Comment by reedseu** [comment]
IOS还没来及测试，目前测试的是安卓，ADT显示 reveiver貌似没进入 而普通的jpush通知是可以响应

**Comment by reedseu** [comment]
IOS还没来及测试，目前测试的是安卓，ADT显示 reveiver貌似没进入 而普通的jpush通知是可以xiang

**Comment by lhw5123** [comment]
@reedseu 不好意思，插件正在完善中。目前 Android 部分基本完成，但 iOS 还在开发，所以如果很急的话，可以试一下 dev 分支下的代码，应该是没有这个问题的。: )

**Comment by reedseu** [comment]
我在仔细描述一下，如果是jpush广播或者是通过jpush API调用发送的alert，点击后都可以正常响应jpush.openNotification，但是通过jmessage的sendSingleTextMessage发过去的消息，点击通知栏，不能正常响应jpush.openNotification

**Comment by lhw5123** [comment]
@reedseu ok，我测试下。

**Comment by lhw5123** [comment]
@reedseu 你好，确实是有这个问题。现在新添加了一个监听事件（jmessage.onOpenMessage），可以监听这个来响应对话消息的点击事件，目前只是提交到了 dev 分支中，可以试试看还有没有什么问题。 : )
> [API 文档](https://github.com/jpush/jmessage-phonegap-plugin/blob/dev/doc/Android_detail_api.md#%E6%B6%88%E6%81%AF%E4%BA%8B%E4%BB%B6)

**Comment by reedseu** [comment]
非常感谢，我们大约月底上线，请问下你们和入主干的时间，我还是期望上线版本用你们的主干版本，谢谢

**Comment by lhw5123** [comment]
大概两周左右吧，主要是 iOS 那边目前正在完善，之后也还需要再测试一下。

**Comment by reedseu** [comment]
非常感谢，最后我发现你的dev分支下IOS API中没有相关的事件回调处理，请问最终会支持么？

**Comment by lhw5123** [comment]
最终肯定是会支持的。 : )

**Comment by reedseu** [comment]
Hello 我切换到你的dev分支，发现你的jmessage-android-1.2.5.jar包中没有import cn.jpush.im.android.api.content.EventNotificationContent; 导致编译失败

**Comment by lhw5123** [comment]
@reedseu 是用命令行编译的吗？有没有图片呢？jar 包里是有这个类的啊。

**Comment by reedseu** [comment]
我再看下，谢谢

**Comment by reedseu** [comment]
我看错了，是这个Class NotificationClickEvent没有

**Comment by lhw5123** [comment]
不好意思，是这个没有引用，现在已经加上了。: )

**Comment by reedseu** [comment]
可以打包了，但发现推送正常，走jmessage收不到消息，这个你们在哪里可以看到消息发送/接受的情况么？

**Comment by lhw5123** [comment]
不好意思，目前还没有统计消息发送和接受情况的功能。
对了，因为 API 做了一些修改，有修改对应的方法吗？有可能是发送没有成功。
可以看下文档：https://github.com/jpush/jmessage-phonegap-plugin/blob/dev/doc/Android_detail_api.md#发送消息
或者参考下 dev 分支里的 Demo 看看。: )

**Comment by reedseu** [comment]
调用
JMessage.sendSingleTextMessage('0110100000t11l4','xxxxx', null, function(){debugger;},function(){debugger;})
返回无法创建对话
我看了下，对端用户是存在的

**Comment by reedseu** [comment]
我知道了
你的API把JMessagePlugin 换成了JMessage

**Comment by reedseu** [comment]
我重新试下

**Comment by reedseu** [comment]
可以了，不过点击可以响应，但无法获知对端用户信息，回调带回的数据中没有

**Comment by lhw5123** [comment]
点击之后，会将消息的数据信息，解析到 window.JMessage.openedMessage 这个对象里。
消息的具体 JSON 格式数据可以看看这里：https://github.com/jpush/jmessage-phonegap-plugin/blob/dev/doc/Android_detail_api.md#发送消息
我觉得可能需要的信息应该都包含了。: )

**Comment by reedseu** [comment]
OK
我看下

**Comment by reedseu** [comment]
非常感谢耐心的指导，最后还有一个问题
 "content": {
        "text": "content",
        "booleanExtras": { },
        "contentType": "text",
        "extras": {
            "a": { }
        },
        "numExtras": { },
        "stringExtras": { }
    },  消息文本没有带过来

**Comment by lhw5123** [comment]
text 就是消息文本啊。

**Comment by reedseu** [comment]
我已经测试了很多次text为空

**Comment by lhw5123** [comment]
var text = window.JMessage.openedMessage.content.text
是这样用的吗？我测了一下，这样应该是有值得呀。

**Comment by reedseu** [comment]
open的时候我暂时不需要获取文本，但是reveive我需要，不过我发现这两种情况下text均为空，一下是我的代码
if (window.JMessage) {
        JMessage.init();
        document.addEventListener('jmessage.onOpenMessage', function(data){
          if (JMessage.openedMessage && JMessage.openedMessage.fromID) {
            $timeout(function(){
              $location.path('/my/chat/' + JMessage.openedMessage.fromID); 
            }, 500);
          }
        });
        
        document.addEventListener('jmessage.onReceiveMessage', function(data){
          if (JMessage.message) $rootScope.$emit('jmessage.singleReceiveMessage', {mbr_id: JMessage.message.fromID, content: JMessage.message.content.text});
          //from_id: "13851447418"
          //from_name: "13851447418"
          //msg_body: Object
          //  text: "xxxxx"
        })
      }

**Comment by lhw5123** [comment]
我是用下面这句测试的，是有值的。

    document.addEventListener("jmessage.onReceiveMessage",
            function(){
                alert(window.JMessage.message.content.text);
            }, false);

**Comment by reedseu** [comment]
我代码的问题，抱歉
