### ISSUE TITLE
jmessage及时性

### ISSUE THREAD

**Issue by reedseu** [jpush/jmessage-phonegap-plugin#14]
后台API调用jpush API 消息到达很及时
jmessage会出现不能及时到达的情况，而且A-B很快 但B-A要等很久

**Comment by lhw5123** [comment]
这个是和具体的网络情况有关，我这里两个手机测试，并没有出现 A - B 很快，但 B - A 很久的情况，或者你用 Demo 来测试下呢？

**Comment by reedseu** [comment]
这个问题确实不太稳定，姑且认为是网络问题，另外还有两个事情
1）当APP在后台运行是，点击jmessage通知，不能把APP置为前台，jpush可以
2）你们的IOS目前可以测试么？我们要测试IOS了

**Comment by lhw5123** [comment]
不好意思，第一个问题刚刚修复了。
iOS 的话可能还要等几天，这边同事还在完善。

**Comment by reedseu** [comment]
你们没有import　Intent吧，你们的怎么几次都出现了提交的代码编译都有问题啊

:compileReleaseJavaWithJavac UP-TO-DATEE:\dev_prj\kly_wap\cordova_app\kuailaiyun\platforms\android\src\cn\jmessage\phonegap\JMessagePlugin.java:236: 错误: 找不到符号
        Intent launch = cordova.getActivity().getPackageManager()

:compileReleaseJavaWithJavac        ^
  符号:   类 Intent
  位置: 类 JMessagePlugin
E:\dev_prj\kly_wap\cordova_app\kuailaiyun\platforms\android\src\cn\jmessage\phonegap\JMessagePlugin.java:236: ����: �Ҳ�������
        Intent launch = cordova.getActivity().getPackageManager()

**Comment by reedseu** [comment]
我本地解决了先，测试通过，感谢

**Comment by lhw5123** [comment]
@reedseu 抱歉，插件习惯直接用编辑器写了，昨天有点自信，没有测命令行编译。
