### ISSUE TITLE
ios下无法执行getRegistrationID回调

### ISSUE THREAD

**Issue by jnotnull** [jpush/jmessage-phonegap-plugin#17]
window.plugins.jPushPlugin.getRegistrationID(function(registerId) {
                $$globalValue.registerId = registerId, $scope.login_func();
            }) 

执行后xcode报如下错误：

ERROR: Plugin 'JPushPlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
-[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["JPushPlugin236206280","JPushPlugin","getRegistrationID",[[]]]

是不是少了jpush的oc文件

备注：我们用的是DEV分支

**Comment by Yasashi** [comment]
你好，请在 JMessagePlugin.js 中 修改方法 `JPushPlugin.prototype.call_native` 为：
```
JPushPlugin.prototype.call_native = function(name, args, callback) {
	if (this.isPlatformIOS()) {
		ret = cordova.exec(callback, this.error_callback, 'JMessagePlugin', name, args);
    }else{
		ret = cordova.exec(callback, this.error_callback, 'JPushPlugin', name, args);
	}
	return ret;
};
```
该 bug 会随后修复
