### ISSUE TITLE
ios下无法安装APP_KEY

### ISSUE THREAD

**Issue by jnotnull** [jpush/jmessage-phonegap-plugin#19]
cordova plugin add  <jmessage-phonegap-plugin路径>   --variable APP_KEY=<your app key>

执行后，APP_KEY并没有被替换

**Comment by Yasashi** [comment]
@jnotnull 你好，
- 在线安装、本地安装我刚刚都试过了，是正常的。
- `APP_KEY=`后面直接填写你的 `appkey` 就行，不加任何空格、符号
- 实在不能自动替换，可以手动在 `JMessageConfig.plist` 文件里修改

**Comment by jnotnull** [comment]
[DEV分支]我是这个格式：    sudo cordova plugin add /Users/jiyanliang/gitlabprj/newjmessage/jmessage-phonegap-plugin --variable APP_KEY=5xxxxxxxa

**Comment by Yasashi** [comment]
- 你这是本地安装，安装前务必先下载最新版本的插件
- 命令不用加 `sudo`，格式没什么问题
- 安装前先删除原有插件

**Comment by jnotnull** [comment]
算了 关闭吧
