### ISSUE TITLE
Badge不能清除

### ISSUE THREAD

**Issue by cydd007** [jpush/jmessage-phonegap-plugin#20]
var ondeviceready=function() {
    if (ionic.Platform.isAndroid() || ionic.Platform.isIOS()) {
      window.plugins.jmessagePlugin.init();
      window.plugins.jPushPlugin.init();
      if (ionic.Platform.isIOS()) {
        window.plugins.jPushPlugin.setDebugModeFromIos();
        window.plugins.jPushPlugin.setApplicationIconBadgeNumber(0);
      } else if (ionic.Platform.isAndroid()){
        window.plugins.jPushPlugin.setDebugMode(true);
        //window.plugins.jPushPlugin.setStatisticsOpen(true);
      }
      window.plugins.jPushPlugin.setAlias('一加科技');
      AutoLogin();
    }
  };
  document.addEventListener("deviceready", ondeviceready, false);
如上代码，IOS下的BADGE不能清除

**Comment by Yasashi** [comment]
@cydd007 
你好，可以尝试
 `
window.JPush.setApplicationIconBadgeNumber(0);
`
