### ISSUE TITLE
[dev]执行JSON.parse(response)返回错误SyntaxError: JSON Parse error: Unexpected identifier "send"

### ISSUE THREAD

**Issue by jnotnull** [jpush/jmessage-phonegap-plugin#21]
IOS下执行JSON.parse(response)报错

    window.JMessage.sendSingleTextMessage(
                usernameForConversation, messageContentString, null,
                function (response) {
                    var msg = JSON.parse(response);
                    messageArray.unshift(msg);
                    refreshConversation();
                }, function (response) {
                    console.log("send message fail" + response);
                    alert("send message fail" + response);
                });

**Comment by Yasashi** [comment]
该方法成功回调接收到的是一条字符串 `"send single text message"`

**Comment by reedseu** [comment]
这个和Android不兼容么？
