### ISSUE TITLE
Android Master问题

### ISSUE THREAD

**Issue by reedseu** [jpush/jmessage-phonegap-plugin#22]
今日正式从dev切换到master发现如下问题
public void sendSingleTextMessage(JSONArray data, final CallbackContext callback) {
........................
            msg.setOnSendCompleteCallback(new BasicCallback() {
                @Override
                public void gotResult(int status, String desc) {
                    if (status == 0) {
                        callback.success(mGson.toJson(msg));
                    } else {
                        callback.error(status + ": " + desc);
                    }
                }
            });//经过测试如上代码导致发送，消息异常，删除后可以正常使用
            ...................................
        } catch (JSONException e) {
            e.printStackTrace();
            callback.error("error reading id json.");
        }
    }

**Comment by lhw5123** [comment]
具体是什么样的异常？

**Comment by reedseu** [comment]
就是发出去，对端没有反应

**Comment by lhw5123** [comment]
@reedseu 有日志吗？我这里测了下，是有反应的。
