### ISSUE TITLE
enterSingleConversation 在iOS 9.3.2 上调用后，没有反应

### ISSUE THREAD

**Issue by merlinchen** [jpush/jmessage-phonegap-plugin#24]
我想创建一个**单聊**，以便在`getAllSingleConversation`中可以取到。在javascript api里没有找到`createSingleConversation`这样的调用，于是我便直接调用了`enterSingleConversation`。但是调用`enterSingleConversation`后，该方法的成功和错误回调均没有被调用。

**Comment by Yasashi** [comment]
iOS 里面没有 `enterSingleConversation` 这个方法，iOS API 文档详见 [iOS API doc](https://github.com/jpush/jmessage-phonegap-plugin/blob/dev/doc/iOS_API.md)
现在建议可以使用 `dev` 分支的代码，里面修复了一些问题。iOS 的 `createSingleConversation` 之类的方法，都是封装在 `sendSingleTextMessage` 等方法内的，可以尝试发一条空信息来创建会话。
