### ISSUE TITLE
iOS 下面收到推送后 badge 不能清除

### ISSUE THREAD

**Issue by cydd007** [jpush/jmessage-phonegap-plugin#25]
iOS 下面收到推送后 badge 不能清除

**Comment by Yasashi** [comment]
setBadge 是设置服务器中的值
setApplicationIconBadgeNumber 是设置本地的值

**Comment by cydd007** [comment]
var ondeviceready=function() {
    if (ionic.Platform.isAndroid() || ionic.Platform.isIOS()) {
      window.plugins.jmessagePlugin.init();
      window.plugins.jPushPlugin.init();
      if (ionic.Platform.isIOS()) {
        window.plugins.jPushPlugin.setDebugModeFromIos();
        window.plugins.jPushPlugin.setApplicationIconBadgeNumber(0);
      } else if (ionic.Platform.isAndroid()){
        window.plugins.jPushPlugin.setDebugMode(true);
        //window.plugins.jPushPlugin.setStatisticsOpen(true);
      }
      window.plugins.jPushPlugin.setAlias('一加科技');
      AutoLogin();
    }
  };

我是这样设置的，badge清除不了

**Comment by Yasashi** [comment]
你这里只是在 ondeviceready 调用，只会在程序启动的时候走一次，之后不会走的。你需要在适当的地方调用，比如：App 从后台进入前台的时候清除；App 处于前台接收到推送的时候清除等。

**Comment by cydd007** [comment]
没用，无论放在哪里，这个badge始终清不掉。

**Comment by cydd007** [comment]
我之前单独用jpush插件，也是这样用法，一切都没有问题的，现在用jmess这个就有问题了。

**Comment by Yasashi** [comment]
jmessage 的插件里面需要用 `window.JPush` 而不是 `window.plugins.jPushPlugin` 来调用方法，因为是沿用了 jpush 插件的文档，文档里没有改过来，抱歉。

**Comment by cydd007** [comment]
是 window.JPushPlugin吧，我看插件的JS文件，导出的定义没有window.JPush啊

**Comment by cydd007** [comment]
经测试，用window.JPush根本没用。

**Comment by cydd007** [comment]
找到原因了，我用的老版的插件，刚刚更新了就可以了。
