### ISSUE TITLE
IOS下不能支持jmessage.onOpenMessage事件么？

### ISSUE THREAD

**Issue by reedseu** [jpush/jmessage-phonegap-plugin#26]
jmessage.onOpenMessage

**Comment by Yasashi** [comment]
参考这里 https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/iOS_API.md#%E7%82%B9%E5%87%BB%E6%8E%A8%E9%80%81%E9%80%9A%E7%9F%A5

**Comment by reedseu** [comment]
但是安卓有啊
而且有些特性也依赖这个，能否支持下
我看了receivemessage支持的

**Comment by reedseu** [comment]
我在说下在安卓中
jmessage.onOpenMessage 和jmessage.onReceiveMessage都能支持，但是在iOS中 只有jmessage.onReceiveMessage，希望能支持jmessage.onOpenMessage 毕竟点击打开普通notification和message业务流程 不一样

**Comment by reedseu** [comment]
看了，jmessage消息通过openNotifaication很多东西都拿不到，既然jmessage已经支持了receive
请也支持open

**Comment by Yasashi** [comment]
后续版本会支持的

**Comment by reedseu** [comment]
好的，谢谢

**Comment by reedseu** [comment]
请问现在进展如何，我们要发布1.1 了

**Comment by pikacode** [comment]
这个 API 在 JMessage iOS SDK 暂未支持的，所以插件暂时也无法支持。

**Comment by reedseu** [comment]
请问下有时间表么？

**Comment by pikacode** [comment]
我始终不太清楚你想要的 `onOpenMessage` 这个方法是干什么的，如果是为了确认是否阅读了消息，只要在自己的数据库里保存就行了。

**Comment by pikacode** [comment]
如果是点击推送横幅获取推送内容那么对应的 API 是 `openNotifaication`，iOS 只有一个通知中心，没有 「一个 Notification 的通知中心 + 一个 Message 的通知中心」这种结构。iOS 通知中心 只能接收 Apple 服务器传过来的内容，格式是固定的，需要额外参数需要自定义。文档里写的有 [openNotifaication](https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/iOS_API.md#%E7%82%B9%E5%87%BB%E6%8E%A8%E9%80%81%E9%80%9A%E7%9F%A5)

**Comment by reedseu** [comment]
点击后跳转到对应的对话页面，比如点击A的消息跳转到到和A的对话页面，点击B的消息跳转到B的对话页面
我们的APP还有系统推送的通知，点击通知跳转到系统的一个指定页面

**Comment by reedseu** [comment]
其实类似微信的点对点聊天

**Comment by reedseu** [comment]
系统通知格式固定我可以通过正则匹配关键内容 决定跳转地址，但是对话就不行了

**Comment by reedseu** [comment]
请问下，这样的方式怎么处理，能通过自定义参数解决么？你们能做相关的封装么？

**Comment by pikacode** [comment]
请问你用 iOS 设备在哪里「点击会话消息」？iOS 的通知中心、通知横幅都是苹果服务器下发的推送，格式都一样。不论你是发的推送，还是发的消息，只要展示在手机的通知中心，就是苹果的推送服务。发消息的时候你会同时收到「消息+推送」，消息在`onReceiveMessage` 获取，推送在 [这里获取](https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/iOS_API.md#%E8%8E%B7%E5%8F%96-apns-%E6%8E%A8%E9%80%81%E5%86%85%E5%AE%B9)

**Comment by reedseu** [comment]
对啊，我点击推送通知的处理，怎么玩？我怎么区分系统通知，还是来自张三，李四的消息

**Comment by reedseu** [comment]
对啊，现在IM消息也有横幅通知，对不对，我点击这个玩意，或者在通知中心点击来自于某个好友发来的IM消息，我要跳转到对应的对话界面，就这么个需求，你说怎么做

**Comment by pikacode** [comment]
- 你需要结合 通知+消息 同时使用，点击通知进入 App，然后接收消息，通过接收到的消息再来判断跳转到哪个页面。
- 但是你去看一下 QQ、微信，都不会这么做，QQ 和微信，你点击了通知，只会跳转到消息列表页面，不会跳转到具体的会话页面。因为如果同时接收了多条消息，点击通知进入 App 以后他获取到多条消息无法判断是点击的哪条进入 App 的。
- 麻烦您做开发的时候做参考实际的 App 案例，另外请您能够根据我们提供的 API 灵活使用。

**Comment by reedseu** [comment]
OK，看了下IOS和安卓确实不一样，应该是IOS系统限制，这个issue先关闭
