### ISSUE TITLE
Jmessage中的Jpush何时更新呢

### ISSUE THREAD

**Issue by hewz** [jpush/jmessage-phonegap-plugin#29]
我需要使用新版Jpush中的getUserNotificationSettings方法，能直接替换Jpush部分吗？谢谢。

**Comment by pikacode** [comment]
这周内应该会更新的，你急用可以用新方法拷贝替换旧方法。

**Comment by hewz** [comment]
ok 谢谢

**Comment by hewz** [comment]
然而20多天过去了还是没有更新啊！

另外如何禁止极光自动开启wifi？

**Comment by pikacode** [comment]
@lhw5123

**Comment by pikacode** [comment]
@hewz JMessage 插件中的 JPush 部分已更新至最新。
https://github.com/jpush/jmessage-phonegap-plugin/releases/tag/untagged-ba5a5e9a2261a6d91520
