### ISSUE TITLE
2.3.0版本jmessage.onReceiveMessage在ios端无法回调

### ISSUE THREAD

**Issue by ZCJuncture** [jpush/jmessage-phonegap-plugin#31]
2.3.0版本分离了jpush和jcore，而分别安装了jpush和jmessage的插件后，此时不管是收到推送还是IM消息，都只能触发jpush.receiveNotification，无法触发jmessage.onReceiveMessage，导致无法获取文字或者图片IM消息的详情。

还有个问题，当处于聊天界面时，能否像安卓那样屏蔽当前聊天用户的推送通知？

**Comment by liuzheng001** [comment]
我也遇到绑定jmessage.onReceiveMessage事件,无触发的情况,lz解决了吗

**Comment by ZCJuncture** [comment]
@liuzheng001 2.3.0的版本没有解决，我暂时回退到2.2.0的版本了

**Comment by liuzheng001** [comment]
2.3以下版本没有使用过,但我发现demo中的一些调用在2.3中有问题,比如var conversations = JSON.parse(response)报错,response直接就是数组,所以感觉2.3版的支持的确不好.

**Comment by ZCJuncture** [comment]
@liuzheng001 你说的这个问题在之前的版本也有。极光IM官方的Cordova插件一直都是Android一套iOS一套，有太多的不一致了，Android都需要JSON.parse()，iOS直接返回的就是json对象或数组，不需要再进行额外的操作，所以我从来都是代码里根据平台进行判断，感觉代码可维护性不是很好。

**Comment by lhw5123** [comment]
确实是有这个问题，这边我们会尽快着手改进。: )

**Comment by huangminlinux** [comment]
@liuzheng001  新版本修复了这个问题， 可以更新一下代码
