### ISSUE TITLE
jmessage在跨应用发送自定义消息时消息接收不到

### ISSUE THREAD

**Issue by xiongjzh** [jpush/jmessage-phonegap-plugin#32]
版本是v2.3.2，不同appkey下，
发送text可以触发jmessage.onReceiveMessage事件，
自定义消息不能触发，消息状态为send_seccuss，jmessage.onReceiveCustomMessage也不触发。接收方完全收不到该消息，historymessage里没有该消息。

**Comment by lhw5123** [comment]
Android 还是 iOS？

**Comment by xiongjzh** [comment]
android

**Comment by lhw5123** [comment]
已修复，可以更新下最新的 JMessagePlugin.java 文件。

**Comment by xiongjzh** [comment]
可以用了
