### ISSUE TITLE
IOS接收到图片信息后怎么显示？

### ISSUE THREAD

**Issue by hejinzhi** [jpush/jmessage-phonegap-plugin#39]
IOS上接收到图片信息，有一个media_id，看上去是七牛的链接？怎么把这个图片显示出来？

![default](https://user-images.githubusercontent.com/18588816/27846890-d55b9f00-616c-11e7-8a96-50cb505d8c06.png)

**Comment by huangminlinux** [comment]
下个版本会处理资源路径问题

**Comment by hejinzhi** [comment]
使用resourcePath显示不出来
<img src=".....">
![default](https://user-images.githubusercontent.com/18588816/28506997-06b4f674-7062-11e7-858f-f1de72182a04.png)

**Comment by huangminlinux** [comment]
- 有添加 `file:// ` 前缀吗？
- 有调用下载图片的接口吗？

**Comment by hejinzhi** [comment]
从上图的错误信息来看，是有file://前缀的。下载图片的接口是什么？

**Comment by huangminlinux** [comment]
我看了一下旧版本的插件，iOS 还没有下载原图的接口。

重构版本才提供了图片音频相关的接口了，切换到 V3 分支。
