### ISSUE TITLE
window.JMessage.getHistoryMessages无返回值

### ISSUE THREAD

**Issue by missjosie** [jpush/jmessage-phonegap-plugin#41]
帐号登入正常，能发送消息，能获取会话列表，只是获取聊天记录无返回值
以下是简化后的代码，毫无反应（username已检查过无问题）

	window.JMessage.getHistoryMessages("single", username, '', 0, 50, function (response) {
			alert("getMessageHistory ok: " + response);
		}, function (response) {
			alert("getMessageHistory fail" + response);
		}
	);

在此先谢过了

**Comment by huangminlinux** [comment]
新版本的修复了大部分问题，建议升级

**Comment by missjosie** [comment]
如何升级呢，我重新安装之后没效果

**Comment by huangminlinux** [comment]
最新版本现在是 3.0.1 ， 这个版本统一 iOS 、Android 的 API，所以有些接口需要重新适配。

**Comment by missjosie** [comment]
你好，已经更新到了新版本，仍然是卡在这个问题

window.JMessage.getHistoryMessages({'type': 'single', 'username': target_username, 'appKey': 'xxxxxxxxx, 'from': 0, 'limit': 10},
		function (msgArr) {
			alert("Get history message ok: " + msgArr);
		}, function (response) {
			alert("Get history message error: " + response.description);
		});

**Comment by lhw5123** [comment]
是 Android 还是 iOS？能提供日志吗？
