### ISSUE TITLE
addReceiveMessageListener触发不了

### ISSUE THREAD

**Issue by hejinzhi** [jpush/jmessage-phonegap-plugin#44]
我已经在页面初始化的时候调用一下代码，然后通过极光后台发送消息给自己，手机上有出现通知，但是没有log信息输出，证明以下代码没有被触发，请问是什么原因？

`    window.JMessage.addReceiveMessageListener((msg: any) => {
      console.log(msg)
    });
`

**Comment by lhw5123** [comment]
是 ionic 几的项目？是使用的 Android 还是 iOS？
我这边用 ionic3 的 blank 模板项目，在 home.ts 中如下添加监听，是可以出发的：
```js
export class HomePage {
  constructor(public navCtrl: NavController) {
      JMessage.addReceiveMessageListener((msg) => {
        alert(msg.text);
      });
  }
}
```

**Comment by hejinzhi** [comment]
我也是ionic3，android。我把监听移到构造函数里也是不行。我重新开个blank项目试试。或者你方便把项目打包发到我QQ邮箱吗？504151911@qq.com

**Comment by lhw5123** [comment]
你的 Cordova 版本是多少？

**Comment by hejinzhi** [comment]
7.0.1

**Comment by lhw5123** [comment]
那应该是了。这里好像有点兼容性的问题，这边调整了下，可以更新插件再试下。: )

**Comment by hejinzhi** [comment]
init的时候一定要填参数才行，现在已经可以监听到信息了
window.JMessage.init({ 'isOpenMessageRoaming': true });
