### ISSUE TITLE
语音信息duration bug

### ISSUE THREAD

**Issue by hejinzhi** [jpush/jmessage-phonegap-plugin#49]
android发送语音时间单位是毫秒，你在接收到的时候除以1000转化成秒这种做法在android发语音给android才有效。但ios发送出来的语音单位本身就是秒，再除以1000，duration就是0了。要统一的是发送信息时的单位，而不是接收到信息再处理。

![default](https://user-images.githubusercontent.com/18588816/29343056-33f7cf7e-8261-11e7-9914-3dc1685d612e.png)

**Comment by lhw5123** [comment]
确实应该是在发送时处理，更新下插件，已修改。

**Comment by hejinzhi** [comment]
OK了
