### ISSUE TITLE
ioinc3 怎么使用JMessage

### ISSUE THREAD

**Issue by jytx** [jpush/jmessage-phonegap-plugin#50]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境
ionic3
* 插件版本:
* 平台（Android / iOS）: Android
* Cordova version (```6.5```): 
* Cordova platform version (```android ~6.1.1```):
* Ionic Version (3.12.0)

## 期望效果
初始化JMessage对象成功
告诉我们你希望达到什么效果。
在使用插件的ts文件最上方声明了
declare let window: any;
## 实际效果
声明后调用JMessage.init({isOpenMessageRoaming: true}) 方法报错,
报错内容主要为:ReferenceError: JMessage is not defined
告诉我们实际是什么效果。

## 重现步骤
1.声明
2.调用
## 背景

你尝试做过些什么？
声明改成:
declare let window: any;
调用处改为:
(<any>window).JMessage.init({isOpenMessageRoaming: true})
以及window.JMessage.init({isOpenMessageRoaming: true})均无效
## Debug logs

包括 Android 或 iOS 的日志：
无

**Comment by lhw5123** [comment]
是用真机或模拟器运行的，还是用浏览器运行的？插件不支持在浏览器中调试。

**Comment by liugogal** [comment]
自己去写ionic-native的插件

**Comment by jytx** [comment]
@liugogal 要怎么自己写ionic-native ,这个我也考虑过,但是找了下教程并没有找到相关的,请问有相关的资料吗
