### ISSUE TITLE
android初始化失败

### ISSUE THREAD

**Issue by eyre** [jpush/jmessage-phonegap-plugin#51]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:3.0.17
* 平台（Android / iOS）:android
* Cordova version (```cordova -v```):7.0.1
* Cordova platform version (```cordova platform ls```): android 6.2.3
* Ionic Version (if using Ionic): 3.9.2

## 期望效果
初始化成功！

## 实际效果
初始化失败!后台打印提示：
[AndroidUtil] AndroidManifest.xml missing required ContentProvider: cn.jpush.android.service.DataProvider

## 重现步骤

  1. 安装插件
  2. 初始化调用
  3. ...
  4. ...

## 背景

你尝试做过些什么？

## Debug logs

包括 Android 或 iOS 的日志：
D/JIGUANG-JCore: [AndroidUtil] action:checkValidManifest
10-10 13:38:50.692 32269-32269/com.chltec.interlart E/JIGUANG-JCore: [AndroidUtil] AndroidManifest.xml missing required ContentProvider: cn.jpush.android.service.DataProvider
10-10 13:38:50.692 32269-32269/com.chltec.interlart W/JIGUANG-JCore: [JCoreInterface] JCore init failed

  * iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by lhw5123** [comment]
感谢反馈，可以更新插件到 v3.0.18 版本。

**Comment by eyre** [comment]
v3.0.18 版本👌
