### ISSUE TITLE
ionic版本的UI demo有吗？

### ISSUE THREAD

**Issue by oceankai** [jpush/jmessage-phonegap-plugin#55]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）:
* Cordova version (```cordova -v```):
* Cordova platform version (```cordova platform ls```):
* Ionic Version (if using Ionic)

## 期望效果

可以提供原生SDK的UI效果

## 实际效果

绘制UI，无法达到原生sdk的UI标准

## 重现步骤

  无

## 背景

绘制UI，无法达到原生sdk的UI标准

## Debug logs

包括 Android 或 iOS 的日志：

  * iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by lhw5123** [comment]
目前没有提供 UI 组件。但网上有很多已有的聊天界面示例可以参考一下。
比如：
- [ionic3-chat](https://github.com/HsuanXyz/ionic3-chat)
- [Ionic Market 中的应用](https://market.ionicframework.com/search?q=chat)
