### ISSUE TITLE
getHistoryMessages 方法参数问题

### ISSUE THREAD

**Issue by miaozhenkun** [jpush/jmessage-phonegap-plugin#56]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境   ionic  android

* 插件版本:
* 平台（Android / iOS）: Android
* Cordova version (```cordova -v```): 7.1.0
* Cordova platform version (```cordova platform ls```):6.2.3
* Ionic Version (if using Ionic)    3.19.0

## 期望效果
getHistoryMessages

从最新的消息开始获取历史消息。

当 limit 为 -1 而 from >= 0 时，返回从 from 开始余下的所有历史消息。如果 from 大于历史消息总数，则返回空数组。 例如：当 from = 0 && limit = -1 时，返回所有历史消息。
告诉我们你希望达到什么效果。

## 实际效果
当 from = 0 && limit = -1 时，返回集合为null

告诉我们实际是什么效果。

## 重现步骤

  1. ...
  2. ...
  3. ...
  4. ...

## 背景

你尝试做过些什么？

## Debug logs

包括 Android 或 iOS 的日志：

  * iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by JoshLipan** [comment]
插件逻辑就是当 from = 0 && limit = -1 时，返回所有历史消息。检查下传参
![default](https://user-images.githubusercontent.com/16323137/42259068-5b7ef3f0-7f91-11e8-8cb4-49d06da0a8b2.png)
