### ISSUE TITLE
Cordova Android 7.0.0 的 AndroidManifest.xml 路径变化问题

### ISSUE THREAD

**Issue by ety001** [jpush/jmessage-phonegap-plugin#57]
使用 Android 7.0.0 ，安装 jmessage 时，有 `no such file or directory, open '/Users/ety001/wwwroot/jianghu_ionic/platforms/android/AndroidManifest.xml'` 报错，根据 Cordova 官方的消息，需要修改配置文件里 AndroidManifest.xml 的路径。

ps: jpush同样存在该问题。

参考：http://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

**Comment by lhw5123** [comment]
感谢反馈，这两天会更新一下。: )

**Comment by lhw5123** [comment]
从 v3.4.0 开始支持 Cordova Android 7.0.0。
