### ISSUE TITLE
corodva build android 是提示错误缺少 引入 cn.jpush.im.android.api.model.UserInfo

### ISSUE THREAD

**Issue by huangzhenxian** [jpush/jmessage-phonegap-plugin#58]
* 插件版本: 3.1.1
* 平台（Android / iOS）:  Android
* Cordova version (```cordova -v```):  8.0.0
* Cordova platform version (```cordova platform ls```): 6.3.2

## 重现步骤
corodva build android 是提示错误缺少 引入 cn.jpush.im.android.api.model.UserInfo

**Comment by lhw5123** [comment]
更新下 v3.1.2 版本。

**Comment by huangzhenxian** [comment]
好的谢谢

**Comment by lhw5123** [comment]
@huangzhenxian 先等一等，v3.1.2 适配 Cordova Android 7.0.0，在之前的项目上会有点问题。我先把这部分的回退了，单独发一个修复 bug 的 v3.1.3。
