### ISSUE TITLE
ionic3，ios版，cant found JMessage解决办法

### ISSUE THREAD

**Issue by oceankai** [jpush/jmessage-phonegap-plugin#59]
ionic3，ios版，cant found JMessage解决办法

1. 在极光官网下载：jmessage-sdk-web-2.1.0.min.js

2. 放入ionic3项目中；

3.index.js 引入：<script src="assets/JMessage/jmessage-sdk-web.2.5.0.min.js"></script>；

4.ts中引入
    //引入jmessage
    declare var JMessage:any;

5.即可调用其他api方法

**Comment by huangminlinux** [comment]
jmessage-sdk-web 的相关问题可以去 https://community.jiguang.cn/ 上提问。
