### ISSUE TITLE
极光离线消息接收不到？ 难道只有通知没有消息？

### ISSUE THREAD

**Issue by xumingyi** [jpush/jmessage-phonegap-plugin#60]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）: android
* Cordova version (```cordova -v```):7.1.0
* Cordova platform version (```cordova platform ls```):
Installed platforms:
  android 6.3.0
  browser 5.0.3
  ios 4.5.4
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0
* Ionic Version (if using Ionic)

cli packages: (C:\11_IONIC_WS\app-doctor\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0 browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.12.0
    npm  : 3.10.10
    OS   : Windows 10
## 期望效果

app离线再启动能收到历史消息

## 实际效果

app离线再启动能收到历史消息的通知，没有触发        this.jmessage.addReceiveMessageListener(this.mReceiveListener);的mReceiveListener
可能是什么原因，难道极光就是只给发了通知没有给发message？

## 重现步骤

1.app杀掉，
2.通过极光开发者服务web 给app发消息
3. app启动，能收到离线消息的通知。但是不触发addReceiveMessageListener(this.mReceiveListener);的mReceiveListener

## 背景

之前的逻辑是极光login成功以后再addReceiveMessageListener(this.mReceiveListener);app启动收不到离线消息。
之后我将addReceiveMessageListener提前到init后立马调用一样收不到。

## Debug logs

包括 Android 或 iOS 的日志：
.....

**Comment by lhw5123** [comment]
收到离线消息的事件，可以试下 [syncOfflineMessage](https://github.com/jpush/jmessage-phonegap-plugin/wiki/Events#syncofflinemessage)。

**Comment by xumingyi** [comment]
非常感谢，解决了我的问题




以上，
徐明义

电话：13022406835
地址：沈阳市浑南区国际软件园B1楼310室
邮箱 : xumingyi@smartens-tek.com 
------------------------------------
 
发件人： Hevin
发送时间： 2018-01-31 13:00
收件人： jpush/jmessage-phonegap-plugin
抄送： FTD_2014; Author
主题： Re: [jpush/jmessage-phonegap-plugin] 极光离线消息接收不到？ 难道只有通知没有消息？ (#60)
收到离线消息的事件，可以试下 syncOfflineMessage。
