### ISSUE TITLE
ionic3使用这个插件报找不到

### ISSUE THREAD

**Issue by gdongy** [jpush/jmessage-phonegap-plugin#69]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）:android
* Cordova version (```cordova -v```):7.1.0
* Cordova platform version (```cordova platform ls```):android
* Ionic Version (if using Ionic)
3.2.0
## 期望效果

告诉我们你希望达到什么效果。
 安装插件初始化并使用功能
## 实际效果
  插件安装之后运行命令就会报插件
  import { JMessagePlugin } from '@ionic-native/jmessage';这是引入的地方
这是报错： typescript: F:/ionic3/testplugin/src/app/app.component.ts, line: 6

告诉我们实际是什么效果。

## 重现步骤

  1. ...
  2. ...
  3. ...
  4. ...

## 背景

你尝试做过些什么？
切换jcore和jmessage版本，3.4.0为版本分界线，测试之前的3.3.0版本和3.4+jmessage版本
## Debug logs

包括 Android 或 iOS 的日志：

  * iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by JoshLipan** [comment]
安装这个规则集成插件，可以先试下官方sample
![image](https://user-images.githubusercontent.com/16323137/42741804-0ec9bda0-88e8-11e8-84f3-baa8af1ce1d5.png)

**Comment by gdongy** [comment]
谢谢，我开始安装的是最新版本，后来指定安装3.3.0，发现不行，后来又切换到3.2.0，这个问题才得到解决；，切换版本的时候没找到这个插件都有哪些可用版本，就试了好几次，建议jmessage插件3.4.0之前版本推荐一个稳定的安装的版本
