### ISSUE TITLE
SDK have not init yet

### ISSUE THREAD

**Issue by LELOG** [jpush/jmessage-phonegap-plugin#70]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）: Android
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): android@6.4.0
* Ionic Version (if using Ionic)
3.20.0
## 期望效果

能用jmessage-phonegap-plugin完成注册，登录，聊天

## 实际效果

出现错误
 error.code:871308
error.description: SDK have not init yet

## 重现步骤

  1.   npm i cordova-plugin-jcore@1.1.12
  2.  cordova plugin add jmessage-phonegap-plugin@3.3.0 --variable APP_KEY=ad04ec4791bc07129ace7087
  3.  npm install --save @jiguang-ionic/jmessage
  4. 安装好以上插件 在构造函数中初始化 this.JMessage.init({ isOpenMessageRoaming: false });
 5 定义一个注册方法实现注册
this.JMessage.register({ username: username, password: '123456', nickname: 'nick1'})
    .then(()=>{
      alert('注册成功');
    })
    .catch(error =>{
      var code = error.code;
      var desc = error.description;
      alert(code+" : "+desc);
    })
## 背景
更换jemssage-phonegat-plugin到3.4.0以上版本则不会出现 SDK have not init yet。
但是jemssage-phonegat-plugin3.4.0以上版本不支持cordova-android@6.4.0

帮助我在cordova-android@6.4.0中使用jemssage-phonegat-plugin

## Debug logs

包括 Android 或 iOS 的日志：
![_20180715172408](https://user-images.githubusercontent.com/37971363/42732421-f4d72548-8853-11e8-9d7d-4382c227e8b0.png)

  * Android: SDK have not init yet
# 

-

**Comment by JoshLipan** [comment]
调用了init也不能成功初始化吗，init前设置[debug模式](https://github.com/jpush/jmessage-phonegap-plugin/wiki/APIs#setdebugmode)抓下原生log看下

**Comment by gdongy** [comment]
如果还没有解决，就把插件卸载重新安装版本3.2.0的，我前几天的时候是插件装上测试没反应，用不了，后来降到3.2.0版本，再测试就好了，我感觉是3.3.0版本的插件有问题

**Comment by JoshLipan** [comment]
https://community.jiguang.cn/t/jmessage-sdk-have-not-init-yet/28281
