### ISSUE TITLE
从多少版本支持安卓八的手机

### ISSUE THREAD

**Issue by MinaAndLuoXia** [jpush/jmessage-phonegap-plugin#76]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
jmessage-phonegap-plugin3.2.0
 cordova-plugin-jcore1.1.12
* 平台（Android / iOS）:
Android 
* Cordova version (```cordova -v```):
7.1.0
* Cordova platform version (```cordova platform ls```):
Installed platforms:
  android 6.3.0
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~5.0.0
  ios ~4.5.1
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0
* Ionic Version (if using Ionic)
3.2.0
## 期望效果
安卓六和安卓八都可以使用
## 背景
现在安卓六可以用，八不好使

**Comment by JoshLipan** [comment]
请集成最新版插件再测试

**Comment by MinaAndLuoXia** [comment]
最新的版本需要cordova android7.x的支持，我不想更新到android7.x，因为其他插件对他的兼容性非常不好

**Comment by JoshLipan** [comment]
参照[这篇文章](https://www.jianshu.com/p/23b117ca27a6)

**Comment by MinaAndLuoXia** [comment]
谢谢，这应该是可行的，我明天会验证他

**Comment by MinaAndLuoXia** [comment]
谢谢，这应该是可行的，我明天会验证他

**Comment by MinaAndLuoXia** [comment]
![bug](https://user-images.githubusercontent.com/42334571/44614893-16f0b280-a860-11e8-8b8f-eb16ae75a9d4.png)
按照他的步骤执行，打包后报错

**Comment by JoshLipan** [comment]
测试了下，确实是新版使用的一些老版本不支持的写法
那还是直接使用老版本，然后[下载原生最新版SDK](https://docs.jiguang.cn/jshare/resources/)替换android/libs/下的jar和so，同样可以得到最新支持
![image](https://user-images.githubusercontent.com/16323137/44643346-c5ccf400-aa02-11e8-81ec-1e6539998b24.png)

**Comment by MinaAndLuoXia** [comment]
按照你说的操作了一下，android6和android8都可以使用了，困扰我四天的问题终于解决了，谢谢
