### ISSUE TITLE
addReceiveMessageListener收到消息，不能马上在当前会话页面显示

### ISSUE THREAD

**Issue by wushunqing** [jpush/jmessage-phonegap-plugin#78]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）: android
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```):
Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

* Ionic Version (if using Ionic):  3.20.0

## 期望效果

直接在聊天页面，当收到聊天消息时候，在手机页面显示

## 实际效果

控制台打印出来，能收到消息，但是页面不显示，需要退到列表页面重新进入该会话，或者唤起键盘，才能显示。

## 重现步骤

 目前每次必现

## 背景

你尝试做过些什么？
目前我在收到消息的是，加了loading可以显示，但是这样效果不太好，不能像QQ微信那样。

## Debug logs

  。。。。。。。。。。。。。。。

**Comment by JoshLipan** [comment]
插件不涉及UI操作，收到消息后显示刷新逻辑需要你自己去控制的

**Comment by lostcixin** [comment]
用angular强制重新刷新页面就好了， ChangeDetectorRef用这个
