### ISSUE TITLE
jmessage和jpush插件冲突

### ISSUE THREAD

**Issue by lingdu0001** [jpush/jmessage-phonegap-plugin#87]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本: 3.5.4
* 平台（Android / iOS）: Android
* Cordova version (```cordova -v```): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (```cordova platform ls```):android 7.1.1
* Ionic Version (if using Ionic) 4.3.1

## 期望效果

同时使用jpush和jmessage 插件

## 实际效果
构建失败 报错信息是
BUILD FAILED in 1s
/Users/Username/demo/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/Username/demo/platforms/android/app/src/main/AndroidManifest.xml:75:9-89:20 Error:
        Element receiver#cn.jpush.android.service.PushReceiver at AndroidManifest.xml:75:9-89:20 duplicated with element declared at AndroidManifest.xml:41:9-55:20
/Users/Username/demo/platforms/android/app/src/main/AndroidManifest.xml:104:9-75 Error:
        Element receiver#cn.jpush.android.service.AlarmReceiver at AndroidManifest.xml:104:9-75 duplicated with element declared at AndroidManifest.xml:56:9-100
/Users/Username/demo/platforms/android/app/src/main/AndroidManifest.xml Error:
        Validation failed, exiting

## 重现步骤
安装最新版本的jpush插件（3.5.0)
安装最新版本的jmessage插件(3.5.4)
cordova build android

## 背景
曾经做过删除platform，重新add，重装ionic cordova npm等操作均无效果。

**Comment by JoshLipan** [comment]
jmessage插件更新至[v3.6.0](https://github.com/jpush/jmessage-phonegap-plugin/releases/tag/v3.6.0)，已适配
